import React from 'react';
import ReactDOM from 'react-dom';
	var data = {
    "gameLength": 190,
    "gameMode": "CLASSIC",
    "mapId": 11,
    "bannedChampions": [{
        "pickTurn": 1,
        "championId": 268,
        "teamId": 100
    }, {
        "pickTurn": 2,
        "championId": 53,
        "teamId": 200
    }, {
        "pickTurn": 3,
        "championId": 39,
        "teamId": 100
    }, {
        "pickTurn": 4,
        "championId": 412,
        "teamId": 200
    }, {
        "pickTurn": 5,
        "championId": 127,
        "teamId": 100
    }, {
        "pickTurn": 6,
        "championId": 25,
        "teamId": 200
    }],
    "gameType": "MATCHED_GAME",
    "gameId": 1718754480,
    "observers": {
        "encryptionKey": "8HjW74tn0r6/gVHekeNMvoO04dpSGoaz"
    },
    "gameQueueConfigId": 4,
    "gameStartTime": 1422984841060,
    "participants": [{
        "masteries": [{
            "rank": 4,
            "masteryId": 4112
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4122
        }, {
            "rank": 1,
            "masteryId": 4124
        }, {
            "rank": 1,
            "masteryId": 4131
        }, {
            "rank": 1,
            "masteryId": 4132
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 1,
            "masteryId": 4141
        }, {
            "rank": 1,
            "masteryId": 4142
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 1,
            "masteryId": 4151
        }, {
            "rank": 2,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4212
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5245
        }, {
            "count": 5,
            "runeId": 5289
        }, {
            "count": 4,
            "runeId": 5290
        }, {
            "count": 9,
            "runeId": 5317
        }, {
            "count": 3,
            "runeId": 5337
        }],
        "spell2Id": 7,
        "profileIconId": 7,
        "summonerName": "B1G Kr1T",
        "championId": 104,
        "teamId": 100,
        "summonerId": 20964624,
        "spell1Id": 4
    }, {
        "masteries": [{
            "rank": 4,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4123
        }, {
            "rank": 1,
            "masteryId": 4133
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 3,
            "masteryId": 4143
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4154
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 3,
            "masteryId": 4312
        }, {
            "rank": 1,
            "masteryId": 4313
        }, {
            "rank": 3,
            "masteryId": 4322
        }, {
            "rank": 1,
            "masteryId": 4324
        }, {
            "rank": 1,
            "masteryId": 4334
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5273
        }, {
            "count": 9,
            "runeId": 5298
        }, {
            "count": 9,
            "runeId": 5316
        }, {
            "count": 2,
            "runeId": 5365
        }, {
            "count": 1,
            "runeId": 8022
        }],
        "spell2Id": 14,
        "profileIconId": 7,
        "summonerName": "Seul",
        "championId": 1,
        "teamId": 100,
        "summonerId": 23461798,
        "spell1Id": 4
    }, {
        "masteries": [{
            "rank": 3,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4123
        }, {
            "rank": 1,
            "masteryId": 4124
        }, {
            "rank": 1,
            "masteryId": 4133
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 3,
            "masteryId": 4143
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4154
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4212
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5273
        }, {
            "count": 9,
            "runeId": 5289
        }, {
            "count": 9,
            "runeId": 5316
        }, {
            "count": 3,
            "runeId": 5357
        }],
        "spell2Id": 14,
        "profileIconId": 502,
        "summonerName": "Rakin",
        "championId": 7,
        "teamId": 100,
        "summonerId": 47409241,
        "spell1Id": 4
    }, {
        "masteries": [{
            "rank": 4,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4123
        }, {
            "rank": 1,
            "masteryId": 4124
        }, {
            "rank": 1,
            "masteryId": 4133
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 2,
            "masteryId": 4143
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4154
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 1,
            "masteryId": 4311
        }, {
            "rank": 3,
            "masteryId": 4312
        }, {
            "rank": 3,
            "masteryId": 4322
        }, {
            "rank": 1,
            "masteryId": 4324
        }, {
            "rank": 1,
            "masteryId": 4334
        }],
        "bot": false,
        "runes": [{
            "count": 6,
            "runeId": 5295
        }, {
            "count": 3,
            "runeId": 5297
        }, {
            "count": 9,
            "runeId": 5315
        }, {
            "count": 3,
            "runeId": 5357
        }, {
            "count": 9,
            "runeId": 5402
        }],
        "spell2Id": 4,
        "profileIconId": 659,
        "summonerName": "Hurleyo",
        "championId": 26,
        "teamId": 100,
        "summonerId": 35169501,
        "spell1Id": 14
    }, {
        "masteries": [{
            "rank": 1,
            "masteryId": 4111
        }, {
            "rank": 3,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4123
        }, {
            "rank": 1,
            "masteryId": 4133
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 3,
            "masteryId": 4143
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4154
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4214
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5273
        }, {
            "count": 9,
            "runeId": 5289
        }, {
            "count": 9,
            "runeId": 5317
        }, {
            "count": 3,
            "runeId": 5357
        }],
        "spell2Id": 4,
        "profileIconId": 594,
        "summonerName": "Nightblue3",
        "championId": 76,
        "teamId": 100,
        "summonerId": 25850956,
        "spell1Id": 11
    }, {
        "masteries": [{
            "rank": 1,
            "masteryId": 4111
        }, {
            "rank": 2,
            "masteryId": 4112
        }, {
            "rank": 4,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 1,
            "masteryId": 4121
        }, {
            "rank": 3,
            "masteryId": 4122
        }, {
            "rank": 1,
            "masteryId": 4132
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4214
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5245
        }, {
            "count": 6,
            "runeId": 5289
        }, {
            "count": 3,
            "runeId": 5295
        }, {
            "count": 9,
            "runeId": 5317
        }, {
            "count": 3,
            "runeId": 5335
        }],
        "spell2Id": 4,
        "profileIconId": 512,
        "summonerName": "Azingy",
        "championId": 64,
        "teamId": 200,
        "summonerId": 22479740,
        "spell1Id": 11
    }, {
        "masteries": [{
            "rank": 4,
            "masteryId": 4112
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4122
        }, {
            "rank": 1,
            "masteryId": 4124
        }, {
            "rank": 1,
            "masteryId": 4131
        }, {
            "rank": 1,
            "masteryId": 4132
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 1,
            "masteryId": 4142
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 1,
            "masteryId": 4151
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4212
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5245
        }, {
            "count": 9,
            "runeId": 5289
        }, {
            "count": 9,
            "runeId": 5317
        }, {
            "count": 3,
            "runeId": 5337
        }],
        "spell2Id": 4,
        "profileIconId": 612,
        "summonerName": "bischus trash",
        "championId": 429,
        "teamId": 200,
        "summonerId": 25479108,
        "spell1Id": 7
    }, {
        "masteries": [{
            "rank": 1,
            "masteryId": 4111
        }, {
            "rank": 4,
            "masteryId": 4113
        }, {
            "rank": 3,
            "masteryId": 4122
        }, {
            "rank": 1,
            "masteryId": 4131
        }, {
            "rank": 1,
            "masteryId": 4132
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 1,
            "masteryId": 4141
        }, {
            "rank": 2,
            "masteryId": 4142
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4212
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5245
        }, {
            "count": 3,
            "runeId": 5289
        }, {
            "count": 6,
            "runeId": 5295
        }, {
            "count": 9,
            "runeId": 5319
        }, {
            "count": 1,
            "runeId": 5335
        }, {
            "count": 2,
            "runeId": 5343
        }],
        "spell2Id": 4,
        "profileIconId": 752,
        "summonerName": "Skinathonian",
        "championId": 92,
        "teamId": 200,
        "summonerId": 23853938,
        "spell1Id": 12
    }, {
        "masteries": [{
            "rank": 3,
            "masteryId": 4113
        }, {
            "rank": 1,
            "masteryId": 4114
        }, {
            "rank": 3,
            "masteryId": 4123
        }, {
            "rank": 1,
            "masteryId": 4124
        }, {
            "rank": 1,
            "masteryId": 4133
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 3,
            "masteryId": 4143
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4154
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4212
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5273
        }, {
            "count": 9,
            "runeId": 5298
        }, {
            "count": 9,
            "runeId": 5316
        }, {
            "count": 3,
            "runeId": 5357
        }],
        "spell2Id": 14,
        "profileIconId": 759,
        "summonerName": "C9 SoIo",
        "championId": 38,
        "teamId": 200,
        "summonerId": 34925733,
        "spell1Id": 4
    }, {
        "masteries": [{
            "rank": 1,
            "masteryId": 4111
        }, {
            "rank": 4,
            "masteryId": 4113
        }, {
            "rank": 3,
            "masteryId": 4122
        }, {
            "rank": 1,
            "masteryId": 4131
        }, {
            "rank": 1,
            "masteryId": 4132
        }, {
            "rank": 3,
            "masteryId": 4134
        }, {
            "rank": 3,
            "masteryId": 4142
        }, {
            "rank": 1,
            "masteryId": 4144
        }, {
            "rank": 3,
            "masteryId": 4152
        }, {
            "rank": 1,
            "masteryId": 4162
        }, {
            "rank": 2,
            "masteryId": 4211
        }, {
            "rank": 2,
            "masteryId": 4214
        }, {
            "rank": 1,
            "masteryId": 4221
        }, {
            "rank": 3,
            "masteryId": 4222
        }, {
            "rank": 1,
            "masteryId": 4232
        }],
        "bot": false,
        "runes": [{
            "count": 9,
            "runeId": 5245
        }, {
            "count": 9,
            "runeId": 5289
        }, {
            "count": 9,
            "runeId": 5317
        }, {
            "count": 3,
            "runeId": 5335
        }],
        "spell2Id": 3,
        "profileIconId": 22,
        "summonerName": "LeBron 23",
        "championId": 40,
        "teamId": 200,
        "summonerId": 24889598,
        "spell1Id": 4
    }],
    "platformId": "NA1"
};

var CurrentGame = React.createClass({

  // get game info
  loadGameData: function() {    
    this.setState({data: data});
  },

  getInitialState: function(){
    return {data: {participants: []}};
  },

  componentDidMount: function() {
    this.loadGameData();
  },

  render: function() {
    return (
      <div className="CurrentGame">
        <h1> Current Game Information</h1>
        <PlayerList data={this.state.data}/>
      </div>
    );
  }
});

var PlayerList = React.createClass({

  render: function() {
    console.log(this.props.data.participants);
    return (
      <ul className="PlayerList">
          {
              this.props.data.participants.map(function(player) {
                return <li key={player.championId}>{player.summonerName}</li>
              })
          }  
      </ul>
    )
  }
});
module.exports  = {
    PlayerList,
    CurrentGame
}